// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0fvG4Cz71p7XGgUM_qOF1f0c6DYOjoSA',
    appId: '1:1088209684753:web:ad3caa5d9998e81c2864b0',
    messagingSenderId: '1088209684753',
    projectId: 'hesega-a7911',
    authDomain: 'hesega-a7911.firebaseapp.com',
    storageBucket: 'hesega-a7911.firebasestorage.app',
    measurementId: 'G-EL46HJ8XNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnueNu0k_n06GZGFpw-wG8vLlbp8O-VMY',
    appId: '1:1088209684753:android:a09d80ce67f9e54d2864b0',
    messagingSenderId: '1088209684753',
    projectId: 'hesega-a7911',
    storageBucket: 'hesega-a7911.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8kTrt2am2whbkEKIIeOhZIQhwuXjbL1g',
    appId: '1:1088209684753:ios:50f5232f74bc753b2864b0',
    messagingSenderId: '1088209684753',
    projectId: 'hesega-a7911',
    storageBucket: 'hesega-a7911.firebasestorage.app',
    iosBundleId: 'com.example.hesega',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8kTrt2am2whbkEKIIeOhZIQhwuXjbL1g',
    appId: '1:1088209684753:ios:50f5232f74bc753b2864b0',
    messagingSenderId: '1088209684753',
    projectId: 'hesega-a7911',
    storageBucket: 'hesega-a7911.firebasestorage.app',
    iosBundleId: 'com.example.hesega',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0fvG4Cz71p7XGgUM_qOF1f0c6DYOjoSA',
    appId: '1:1088209684753:web:8078c97ea06ba0f12864b0',
    messagingSenderId: '1088209684753',
    projectId: 'hesega-a7911',
    authDomain: 'hesega-a7911.firebaseapp.com',
    storageBucket: 'hesega-a7911.firebasestorage.app',
    measurementId: 'G-KRZ6Z7Y9K4',
  );
}
